// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/data/db_models/comment_db_model.dart';
import 'src/data/db_models/post_db_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2931737965463348577),
    name: 'CommentDbModel',
    lastPropertyId: const obx_int.IdUid(10, 6880003786568148111),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1967802958144400861),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4300935405449512087),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6738964908160093831),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 552684578350037588),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5247634846607059819),
        name: 'postId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6880003786568148111),
        name: 'commentId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3556191122092791761),
    name: 'PostDbModel',
    lastPropertyId: const obx_int.IdUid(10, 5414023704649942732),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8291367764273655593),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 338345024824131249),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7864957524971622603),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7899252918888757548),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4258002409561423645),
        name: 'userId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5414023704649942732),
        name: 'postId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 4760798503526193101),
        name: 'comments',
        targetId: const obx_int.IdUid(1, 2931737965463348577),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3556191122092791761),
    lastIndexId: const obx_int.IdUid(1, 6888442964382203585),
    lastRelationId: const obx_int.IdUid(1, 4760798503526193101),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [6888442964382203585],
    retiredPropertyUids: const [
      4661444735342521992,
      6140632778781903262,
      5692164489295845241,
      2204212711337623366,
      8994773502960936797,
      943108135584355363,
      2685243696958959412,
      5672236274598809328,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CommentDbModel: obx_int.EntityDefinition<CommentDbModel>(
      model: _entities[0],
      toOneRelations: (CommentDbModel object) => [],
      toManyRelations: (CommentDbModel object) => {},
      getId: (CommentDbModel object) => object.id,
      setId: (CommentDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (CommentDbModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emailOffset = fbb.writeString(object.email);
        final bodyOffset = fbb.writeString(object.body);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, bodyOffset);
        fbb.addInt64(8, object.postId);
        fbb.addInt64(9, object.commentId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final postIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final commentIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = CommentDbModel(
          id: idParam,
          postId: postIdParam,
          commentId: commentIdParam,
          name: nameParam,
          email: emailParam,
          body: bodyParam,
        );

        return object;
      },
    ),
    PostDbModel: obx_int.EntityDefinition<PostDbModel>(
      model: _entities[1],
      toOneRelations: (PostDbModel object) => [],
      toManyRelations: (PostDbModel object) => {
        obx_int.RelInfo<PostDbModel>.toMany(1, object.id): object.comments,
      },
      getId: (PostDbModel object) => object.id,
      setId: (PostDbModel object, int id) {
        object.id = id;
      },
      objectToFB: (PostDbModel object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, bodyOffset);
        fbb.addBool(7, object.isFavorite);
        fbb.addInt64(8, object.userId);
        fbb.addInt64(9, object.postId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final postIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = PostDbModel(
          id: idParam,
          userId: userIdParam,
          postId: postIdParam,
          title: titleParam,
          body: bodyParam,
          isFavorite: isFavoriteParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<PostDbModel>(
          object.comments,
          store,
          obx_int.RelInfo<PostDbModel>.toMany(1, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CommentDbModel] entity fields to define ObjectBox queries.
class CommentDbModel_ {
  /// See [CommentDbModel.id].
  static final id = obx.QueryIntegerProperty<CommentDbModel>(
    _entities[0].properties[0],
  );

  /// See [CommentDbModel.name].
  static final name = obx.QueryStringProperty<CommentDbModel>(
    _entities[0].properties[1],
  );

  /// See [CommentDbModel.email].
  static final email = obx.QueryStringProperty<CommentDbModel>(
    _entities[0].properties[2],
  );

  /// See [CommentDbModel.body].
  static final body = obx.QueryStringProperty<CommentDbModel>(
    _entities[0].properties[3],
  );

  /// See [CommentDbModel.postId].
  static final postId = obx.QueryIntegerProperty<CommentDbModel>(
    _entities[0].properties[4],
  );

  /// See [CommentDbModel.commentId].
  static final commentId = obx.QueryIntegerProperty<CommentDbModel>(
    _entities[0].properties[5],
  );
}

/// [PostDbModel] entity fields to define ObjectBox queries.
class PostDbModel_ {
  /// See [PostDbModel.id].
  static final id = obx.QueryIntegerProperty<PostDbModel>(
    _entities[1].properties[0],
  );

  /// See [PostDbModel.title].
  static final title = obx.QueryStringProperty<PostDbModel>(
    _entities[1].properties[1],
  );

  /// See [PostDbModel.body].
  static final body = obx.QueryStringProperty<PostDbModel>(
    _entities[1].properties[2],
  );

  /// See [PostDbModel.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<PostDbModel>(
    _entities[1].properties[3],
  );

  /// See [PostDbModel.userId].
  static final userId = obx.QueryIntegerProperty<PostDbModel>(
    _entities[1].properties[4],
  );

  /// See [PostDbModel.postId].
  static final postId = obx.QueryIntegerProperty<PostDbModel>(
    _entities[1].properties[5],
  );

  /// see [PostDbModel.comments]
  static final comments = obx.QueryRelationToMany<PostDbModel, CommentDbModel>(
    _entities[1].relations[0],
  );
}
